{{- if .Values.operator.applyPriorityClass }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "operator.name" . }}
value: {{ .Values.operator.priorityClassValue }}
{{- end }}